### ISSUE TITLE
array in where clause

### ISSUE THREAD

**Issue by lexo13** [roojs/PDO_DataObject#1]
HI,

is it possible to put an array in WHERE clause like this ?

->where(['filed1' => $value1, 'filed2' => $value2])

**Comment by roojs** [comment]
normally that's what 'set' is used for: 
$do->set(['filed1' => $value1, 'filed2' => $value2])->fetchAll();
results in SELECT WHERE filed1 = $value And filed2 =  $value2 ...

Although 'set'  does validate the column value - so you can only use the table columns in there.

The Update/Delete conditions do have different rules where they either work from primary keys or where() values (using WHERE_ADD_ONLY)
