### ISSUE TITLE
Method get(value of primary) not working

### ISSUE THREAD

**Issue by stefanpetre** [roojs/PDO_DataObject#3]
Hi,

Using `$table->get(val)` without the column name throws an error.  The keys array returned by the method `keys()` is of a different format then the `get()` method expects it to be. `$k = $keys[0];` is null. I used `if (!key_exists(0, $keys)) { $keys = array_keys($keys); }` for the moment.

The PEAR DO `keys()` returned array('id'), while your implementation returns array('id'=>'N').

BTW: nice work.

**Comment by roojs** [comment]
The code in DataObjects seems to return array_keys(.... ini data ...) - so they should match

the key's method can set a temporary 'keys' value - which is not validated - I've modified that - see if it helps find the cause.
