### ISSUE TITLE
Addition of "final" keyword to many methods breaks compatibility with DB_DataObject

### ISSUE THREAD

**Issue by gbxyz** [roojs/PDO_DataObject#7]
Hi @roojs,

Many of the methods on `PDO_DataObjec` which are re-implementations of methods with the same name from `DB_DataObject` have the `final` keyword. This is causing backwards compatibility issues for us since we overload many of them in order to implement our business logic.

I can't see any info on why the `final` keywords were added to these methods: what's the reason?

**Comment by roojs** [comment]
I think some of the core one's on insert/update/delete/fetch etc. were the result of a how I originally used DataObjects in early projects, in a similar way by over-riding these methods 
- that eventually lead to quite a few bugs. - horrible unexpected behaviour etc. 

Adding 'final' enabled me to find and fix code that did that a little quicker.

What I tend to do now, is in the controller call methods like 'beforeInsert() / onInsert()' etc. explicitly if they exist. 

Let me know your thoughts - I'll see if there is any other way of doing this.

**Comment by roojs** [comment]
Done
